# Generated by Django 4.2.15 on 2024-10-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_order_user_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
